"""initial_schema_all_tables

Revision ID: 4d800a249d73
Revises: 
Create Date: 2026-04-28 00:24:47.878030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '4d800a249d73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension for embedding columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acknowledgement_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_key', sa.Text(), nullable=False),
    sa.Column('context_tag', sa.Text(), nullable=False),
    sa.Column('audio_r2_key', sa.Text(), nullable=False),
    sa.Column('transcript_telugu', sa.Text(), nullable=False),
    sa.Column('transcript_english', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_key')
    )
    op.create_table('brand_partnerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=False),
    sa.Column('contract_status', sa.Enum('active', 'paused', 'expired', name='contract_status_enum', create_constraint=True), nullable=False),
    sa.Column('weight_multiplier', sa.Numeric(), nullable=False),
    sa.Column('per_order_payout_inr', sa.Integer(), nullable=False),
    sa.Column('category_scope', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('region_scope', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('contract_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_orders_attributed', sa.Integer(), nullable=False),
    sa.Column('total_payout_inr', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canonical_skus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('display_name_en', sa.Text(), nullable=False),
    sa.Column('display_names_local', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('pack_size', sa.Text(), nullable=True),
    sa.Column('typical_price_band_min_inr', sa.Integer(), nullable=True),
    sa.Column('typical_price_band_max_inr', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('brand_partnership_weight', sa.Numeric(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_index('ix_canonical_skus_brand', 'canonical_skus', ['brand'], unique=False)
    op.create_index('ix_canonical_skus_category', 'canonical_skus', ['category'], unique=False)
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('default_payer_user_id', sa.UUID(), nullable=True),
    sa.Column('primary_locale', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('approval_threshold_inr', sa.Integer(), nullable=False),
    sa.Column('care_features_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_payer_user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('maps_to_category', sa.Text(), nullable=False),
    sa.Column('maps_to_brand', sa.Text(), nullable=True),
    sa.Column('default_pack_size', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_term_lang', 'vocabulary_terms', ['term', 'language'], unique=False)
    op.create_table('provider_sku_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_sku_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('swiggy_instamart_mcp', 'swiggy_food_mcp', 'swiggy_dineout_mcp', 'ondc', 'manual_ops', name='provider_enum', create_constraint=True), nullable=False),
    sa.Column('provider_sku_id', sa.Text(), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('last_price_inr', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canonical_sku_id'], ['canonical_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ordering_user', 'payer', 'both', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('relationship_label', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_phone_e164', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('voice_print_id', sa.Text(), nullable=True),
    sa.Column('dietary_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('care_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('affected_user_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('silence', 'duplicate_order', 'cognitive_pattern', 'upi_rejection_pattern', 'payer_balance_low', 'delivery_failed', 'unusual_value', 'unusual_hour', 'provider_outage', name='signal_type_enum', create_constraint=True), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warn', 'urgent', name='severity_enum', create_constraint=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_to_family_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_payers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upi_handle', sa.Text(), nullable=True),
    sa.Column('is_default_payer', sa.Boolean(), nullable=False),
    sa.Column('category_routing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_approve_threshold_inr', sa.Integer(), nullable=False),
    sa.Column('trust_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('ordering_user_id', sa.UUID(), nullable=False),
    sa.Column('payer_user_id', sa.UUID(), nullable=False),
    sa.Column('related_order_id', sa.UUID(), nullable=True),
    sa.Column('related_voice_session_id', sa.UUID(), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=False),
    sa.Column('upi_handle_charged', sa.Text(), nullable=True),
    sa.Column('razorpay_request_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'sent_to_payer', 'approved', 'rejected', 'expired', 'paid', 'failed', name='payment_status_enum', create_constraint=True), nullable=False),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payer_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['ordering_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], use_alter=True),
    sa.ForeignKeyConstraint(['related_voice_session_id'], ['voice_sessions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('related_voice_session_id', name='uq_payment_voice_session')
    )
    op.create_table('voice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('ordering_user_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_message_id', sa.Text(), nullable=True),
    sa.Column('input_mode', sa.Enum('text', 'voice', name='input_mode_enum', create_constraint=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('audio_r2_key', sa.Text(), nullable=True),
    sa.Column('audio_duration_sec', sa.Numeric(), nullable=True),
    sa.Column('transcription_raw', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('language_detected', sa.String(length=10), nullable=True),
    sa.Column('transcription_confidence', sa.Numeric(), nullable=True),
    sa.Column('parsed_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_cart', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_state', sa.String(length=30), nullable=True),
    sa.Column('pipeline_latency_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('order_placed', 'cancelled', 'amended', 'failed', 'still_pending', 'clarification_requested', 'audio_unavailable', 'payment_rejected', name='session_outcome_enum', create_constraint=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('ack_message_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['ordering_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('ordering_user_id', sa.UUID(), nullable=False),
    sa.Column('voice_session_id', sa.UUID(), nullable=True),
    sa.Column('payment_request_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('provider_order_id', sa.Text(), nullable=True),
    sa.Column('cart_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_inr', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending_payment', 'pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled', 'failed', name='order_status_enum', create_constraint=True), nullable=False),
    sa.Column('required_explicit_approval', sa.Boolean(), nullable=False),
    sa.Column('delivery_address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['ordering_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_request_id'], ['payment_requests.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('voice_sessions')
    op.drop_table('payment_requests')
    op.drop_table('family_payers')
    op.drop_table('care_signals')
    op.drop_table('users')
    op.drop_table('provider_sku_mappings')
    op.drop_index('ix_vocab_term_lang', table_name='vocabulary_terms')
    op.drop_table('vocabulary_terms')
    op.drop_table('families')
    op.drop_index('ix_canonical_skus_category', table_name='canonical_skus')
    op.drop_index('ix_canonical_skus_brand', table_name='canonical_skus')
    op.drop_table('canonical_skus')
    op.drop_table('brand_partnerships')
    op.drop_table('acknowledgement_variants')
    # ### end Alembic commands ###
